# Generated by Django 4.2.7 on 2023-11-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_calendar_project_money_alter_project_functions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='task',
            field=models.CharField(default='', max_length=100, verbose_name='task'),
            preserve_default=False,
        ),
    ]
