# Generated by Django 4.2.7 on 2023-11-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_calendar_almanac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almanac',
            name='task',
            field=models.CharField(max_length=100, verbose_name='Название предмета'),
        ),
    ]
